#!/usr/bin/env python
"""H2: does extraction efficiency DECLINE above r ~ 0.64? (docs/COHERENCE_STRENGTH.md §5)

F22a observed fraction-of-reachable-signal falling 78.9% -> 44.6% -> 40.4% as the
ceiling (2.494 -> 2.789 -> 3.107) outran the model. That observation is NOT a
finding: F22's pre-registered rule was written for Delta, and this metric was
adopted after Delta returned INCONCLUSIVE. Post-hoc metric selection does not
become sound because the number is larger.

FRESH-SEED REQUIREMENT. The hypothesis was generated by seeds 0-7. This tests it
on seeds 8-15 ONLY. Confirming a hypothesis on the data that generated it is not
a test, and --allow-stale exists solely to reproduce the biased original number
for comparison, never to decide the verdict.

    fraction = (model_gain - shape_oracle) / (fair_ceiling - shape_oracle)

with fair_ceiling = the shape+appearance oracle recomputed PER WORLD (the
ABO_COUPLING.md A5 rule: never compare against a reference computed elsewhere).

DECISION RULE, fixed before the fresh seeds were run:

    DECLINE CONFIRMED  fraction(r=0.636) - fraction(r=0.992) >= 0.20
                       AND Welch t >= 2.5, on fresh seeds
    NULL               |difference| < 0.08
    INCONCLUSIVE       otherwise

Usage:  .venv/bin/python scripts/f23_extraction_test.py [--allow-stale]
"""
from __future__ import annotations

import argparse
import glob
import json
import math
import os
import re
import statistics as st
import sys

import numpy as np

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "src"))
sys.path.insert(0, os.path.dirname(__file__))

from oracle_ceiling import best_oracle  # noqa: E402
from oracle_ceiling import gain as gain_ratio  # noqa: E402
from probe_appearance import encode_z  # noqa: E402
from render_fidelity_eval import behavior_from_z, load_arrays, shape_onehot  # noqa: E402

# (label, r, dataset, tag)
POINTS = [
    ("r=0.636", 0.636, "data/pm_f22_g15", "g15_cont"),
    ("r=0.992", 0.992, "data/pm_f22_loud", "loud_cont"),
]
FRESH_MIN_SEED = 8          # seeds 0-7 generated the hypothesis
CONF_DIFF, CONF_T, NULL_MAX = 0.20, 2.5, 0.08


def welch_t(x, y):
    if len(x) < 2 or len(y) < 2:
        return float("nan")
    se = math.sqrt(st.variance(x) / len(x) + st.variance(y) / len(y))
    return (st.mean(x) - st.mean(y)) / se if se > 0 else float("nan")


def seed_of(path: str) -> int:
    m = re.search(r"_s(\d+)/", path)
    return int(m.group(1)) if m else -1


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--allow-stale", action="store_true",
                    help="include seeds 0-7 (the hypothesis-generating set). "
                         "For reproducing the biased original number ONLY -- "
                         "the verdict is suppressed when set.")
    args = ap.parse_args()

    from pseudomarble.config import ModelConfig
    from pseudomarble.models.mlx_net import build_model

    fracs, report = {}, {"points": {}, "fresh_min_seed": FRESH_MIN_SEED,
                         "rule": {"conf_diff": CONF_DIFF, "conf_t": CONF_T,
                                  "null_max": NULL_MAX}}
    print(f"{'point':10s} {'n':>2s} {'shape':>7s} {'ceiling':>8s} {'reach':>7s} "
          f"{'gain':>7s} {'fraction':>9s}")

    for label, r, data, tag in POINTS:
        cks = sorted(glob.glob(f"runs/f22/{tag}_s*/model.safetensors"))
        if not args.allow_stale:
            cks = [c for c in cks if seed_of(c) >= FRESH_MIN_SEED]
        if not cks:
            print(f"{label}: no fresh seeds (>= s{FRESH_MIN_SEED}) -- run them first")
            return

        imgs, Yb, Ya, tr, te, ds = load_arrays(data)
        S = shape_onehot(ds)
        shape_gain = best_oracle(S[tr], Yb[tr], S[te], Yb[te], quad=False)[0]
        SA = np.concatenate([S, Ya], 1)
        ceiling = best_oracle(SA[tr], Yb[tr], SA[te], Yb[te])[0]
        reach = ceiling - shape_gain

        fr, gains = [], []
        for ck in cks:
            m = build_model(ModelConfig(image_size=128))
            m.load_weights(ck)
            g = gain_ratio(Yb[tr], Yb[te], behavior_from_z(m, encode_z(m, imgs))[te])
            gains.append(g)
            fr.append((g - shape_gain) / reach if reach > 0 else float("nan"))
        fracs[label] = fr
        report["points"][label] = {
            "r": r, "n": len(fr), "seeds": [seed_of(c) for c in cks],
            "shape_oracle": float(shape_gain), "fair_ceiling": float(ceiling),
            "reachable": float(reach), "gain_mean": float(np.mean(gains)),
            "fraction_mean": float(st.mean(fr)),
            "fraction_sd": float(st.stdev(fr)) if len(fr) > 1 else 0.0,
            "fraction_per_seed": fr}
        print(f"{label:10s} {len(fr):2d} {shape_gain:7.3f} {ceiling:8.3f} {reach:7.3f} "
              f"{np.mean(gains):7.3f} {st.mean(fr) * 100:8.1f}%")

    a, b = fracs["r=0.636"], fracs["r=0.992"]
    diff, t = st.mean(a) - st.mean(b), welch_t(a, b)
    print(f"\nfraction(0.636) - fraction(0.992) = {diff:+.3f}   Welch t {t:.2f}")

    if args.allow_stale:
        verdict = ("VERDICT SUPPRESSED -- --allow-stale includes the "
                   "hypothesis-generating seeds. This number is biased upward by "
                   "selection and cannot decide anything.")
    elif diff >= CONF_DIFF and t >= CONF_T:
        verdict = ("DECLINE CONFIRMED -- extraction efficiency falls as coupling "
                   "rises past r~0.64: the ceiling outruns the model. Build "
                   "Option B at r~0.64, not higher.")
    elif abs(diff) < NULL_MAX:
        verdict = ("NULL -- no decline. The F22a observation was an artifact of "
                   "the hypothesis-generating seeds; extraction is flat above "
                   "r~0.64 and coupling strength beyond that is simply neutral.")
    else:
        verdict = "INCONCLUSIVE -- below the prefixed bar. Report; do not claim."

    print(f"\n[H2] {verdict}")
    report.update({"difference": float(diff), "welch_t": float(t),
                   "verdict": verdict, "stale_included": bool(args.allow_stale),
                   "note": ("H1 is registered separately in "
                            "scripts/f23_coherence_test.py; neither result may be "
                            "cited as support for the other.")})
    os.makedirs("runs/f23", exist_ok=True)
    json.dump(report, open("runs/f23/f23_extraction.json", "w"), indent=2)
    print("[H2] wrote runs/f23/f23_extraction.json")


if __name__ == "__main__":
    main()
